In [3]:
import pandas as pd
import numpy as np
import os

## Case Study Practice

In [12]:
student1 = [80, 70, 90]
student2 = [60, 85, 75]
student3 = [95, 88, 92]
student4 = [70, 60, 65]

students = np.array([student1, student2, student3, student4])
subject = ['Math', 'English', 'Science']

print(students.shape)
students

(4, 3)


array([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])

In [13]:
scores = np.sum(students, axis=1)
n = 1
for i in scores:
    print(f'Student{n} :{i}')
    n+=1

Student1 :240
Student2 :220
Student3 :275
Student4 :195


In [17]:
math_weight = 2
students_copy = students.copy()
students_copy[:,0] = np.dot(math_weight, students_copy[:,0])
students_copy

array([[160,  70,  90],
       [120,  85,  75],
       [190,  88,  92],
       [140,  60,  65]])

In [20]:
average = np.mean(students_copy, axis=0)

i = 0
for avg in average:
    print(f"Average {subject[i]}: {avg}")
    i +=1

Average Math: 152.5
Average English: 75.75
Average Science: 80.5


In [33]:
weight = np.array([[0.5], [0.3], [0.2]])
weight.shape

weighted_score = np.matmul(students, weight)
weighted_score.shape

i = 1
for grade in weighted_score:
    print(f'Student{1}: {grade}')
    i+=1

weights = np.array([0.5,0.3, 0.2])
weights.shape
weighted_score = np.matmul(students, weights)
weighted_score.shape

print("")
i = 1
for grade in weighted_score:
    print(f'Student{1}: {grade}')
    i+=1

Student1: [79.]
Student1: [70.5]
Student1: [92.3]
Student1: [66.]

Student1: 79.0
Student1: 70.5
Student1: 92.30000000000001
Student1: 66.0


In [36]:
diff = np.subtract(students[0,:], students[3,:])
diff

array([10, 10, 25])

In [39]:
np.random.seed(24)

In [40]:
subjects =  ['Math', 'English', 'Science', 'TD']
scores = np.random.randint(45,99, size=(5,4))
scores


array([[79, 48, 45, 68],
       [62, 62, 46, 81],
       [60, 49, 92, 80],
       [63, 56, 80, 96],
       [60, 84, 54, 63]], dtype=int32)

In [42]:
total = np.sum(scores, axis=1)

i =1
for score in total:
    print(f"Student{i}: {score}")
    i+=1

Student1: 240
Student2: 251
Student3: 281
Student4: 295
Student5: 261


In [43]:
science_weight = 3
scores[:,2] = np.dot(science_weight, scores[:,2])
scores

array([[ 79,  48, 135,  68],
       [ 62,  62, 138,  81],
       [ 60,  49, 276,  80],
       [ 63,  56, 240,  96],
       [ 60,  84, 162,  63]], dtype=int32)

In [44]:
total = np.sum(scores, axis=1)

i =1
for score in total:
    print(f"Student{i}: {score}")
    i+=1

Student1: 330
Student2: 343
Student3: 465
Student4: 455
Student5: 369


In [45]:
new_weights = np.array([0.4, 0.2, 0.3, 0.1])
final = np.matmul(scores, new_weights)
final

array([ 88.5,  86.7, 124.6, 118. ,  95.7])

## Basic Data Exploration

In [3]:
data = pd.read_csv("student.csv")

In [4]:
data.head(10)

Unnamed: 0   Student_ID Learning_Track  Study_Hours_Per_Week  \
0           0  AIE_2024000    Traditional             95.058535   
1           1  AIE_2024001    Accelerated             37.186831   
2           2  AIE_2024002    Accelerated             38.323140   
3           3  AIE_2024003    Traditional             27.881352   
4           4  AIE_2024004    Traditional             24.498567   
5           5  AIE_2024005    Traditional             25.980044   
6           6  AIE_2024006    Traditional             92.883167   
7           7  AIE_2024007    Accelerated             42.114543   
8           8  AIE_2024008    Accelerated             38.902533   
9           9  AIE_2024009    Accelerated             32.865274   

   Performance_Score  Projects_Completed  Age  \
0          92.514050                12.0   30   
1          70.156243                12.0   30   
2                NaN                12.0   32   
3          90.623192                10.0   28   
4          81.461708                 4.0   30   
5          93.681531                 2.0   31   
6          58.144770                 8.0   30   
7          -7.746672                13.0   26   
8          74.150912                16.0   23   
9          76.385080                10.0   26   

   Prior_Programming_Experience_Yrs  Online_Courses_Completed  
0                          0.131237                         0  
1                          1.863695                         3  
2                          3.071151                         8  
3                          0.298920                         2  
4                          0.775986                         1  
5                          1.241782                         1  
6                          1.306246                         5  
7                          0.167271                         3  
8                          6.883668                         4  
9                          2.856132                         3

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Unnamed: 0                        500 non-null    int64  
 1   Student_ID                        500 non-null    object 
 2   Learning_Track                    500 non-null    object 
 3   Study_Hours_Per_Week              474 non-null    float64
 4   Performance_Score                 481 non-null    float64
 5   Projects_Completed                483 non-null    float64
 6   Age                               500 non-null    int64  
 7   Prior_Programming_Experience_Yrs  500 non-null    float64
 8   Online_Courses_Completed          500 non-null    int64  
dtypes: float64(4), int64(3), object(2)
memory usage: 35.3+ KB


In [6]:
data.describe()

Unnamed: 0  Study_Hours_Per_Week  Performance_Score  \
count  500.000000            474.000000         481.000000   
mean   249.500000             31.929978          72.497669   
std    144.481833             19.432986          18.055057   
min      0.000000              0.000000          -9.276106   
25%    124.750000             22.046598          64.687299   
50%    249.500000             27.706396          73.583514   
75%    374.250000             37.092870          82.721726   
max    499.000000            118.414671         118.863496   

       Projects_Completed         Age  Prior_Programming_Experience_Yrs  \
count          483.000000  500.000000                        500.000000   
mean            11.014493   26.434000                          1.788520   
std              7.399520    4.874954                          1.867475   
min              1.000000   18.000000                          0.002475   
25%              7.000000   22.000000                          0.495720   
50%             10.000000   26.000000                          1.227495   
75%             12.000000   31.000000                          2.423013   
max             49.000000   34.000000                         11.775799   

       Online_Courses_Completed  
count                500.000000  
mean                   2.938000  
std                    1.655184  
min                    0.000000  
25%                    2.000000  
50%                    3.000000  
75%                    4.000000  
max                   11.000000

In [7]:
data.columns

Index(['Unnamed: 0', 'Student_ID', 'Learning_Track', 'Study_Hours_Per_Week',
       'Performance_Score', 'Projects_Completed', 'Age',
       'Prior_Programming_Experience_Yrs', 'Online_Courses_Completed'],
      dtype='object')

In [ ]:
# data.drop('Unnamed: 0', axis=1, inplace= True)

In [9]:
data.columns

Index(['Unnamed: 0', 'Student_ID', 'Learning_Track', 'Study_Hours_Per_Week',
       'Performance_Score', 'Projects_Completed', 'Age',
       'Prior_Programming_Experience_Yrs', 'Online_Courses_Completed'],
      dtype='object')

In [10]:
#Number of students in each learning track
data.groupby("Learning_Track")['Student_ID'].nunique()

Learning_Track
Accelerated    207
Traditional    293
Name: Student_ID, dtype: int64

In [28]:
data.isna().sum()

Student_ID                          0
Learning_Track                      0
Study_Hours_Per_Week                0
Performance_Score                   0
Projects_Completed                  0
Age                                 0
Prior_Programming_Experience_Yrs    0
Online_Courses_Completed            0
dtype: int64

In [29]:
data.dtypes

Student_ID                           object
Learning_Track                       object
Study_Hours_Per_Week                float64
Performance_Score                   float64
Projects_Completed                  float64
Age                                   int64
Prior_Programming_Experience_Yrs    float64
Online_Courses_Completed              int64
dtype: object

In [13]:
data['Study_Hours_Per_Week'].fillna(data['Study_Hours_Per_Week'].mean(), inplace=True )

C:\Users\owner\AppData\Local\Temp\ipykernel_2068\765200214.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Study_Hours_Per_Week'].fillna(data['Study_Hours_Per_Week'].mean(), inplace=True )


In [16]:
data['Performance_Score'].fillna(np.mean(data['Performance_Score']), inplace=True)


C:\Users\owner\AppData\Local\Temp\ipykernel_2068\23995210.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Performance_Score'].fillna(np.mean(data['Performance_Score']), inplace=True)


In [18]:
data['Projects_Completed'].fillna(np.mean(data['Projects_Completed']), inplace=True)


C:\Users\owner\AppData\Local\Temp\ipykernel_2068\3197425202.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Projects_Completed'].fillna(np.mean(data['Projects_Completed']), inplace=True)


In [30]:
data.isna().sum()

Student_ID                          0
Learning_Track                      0
Study_Hours_Per_Week                0
Performance_Score                   0
Projects_Completed                  0
Age                                 0
Prior_Programming_Experience_Yrs    0
Online_Courses_Completed            0
dtype: int64

In [34]:
data.describe()

Study_Hours_Per_Week  Performance_Score  Projects_Completed  \
count            500.000000         500.000000          500.000000   
mean              31.929978          72.497669           11.014493   
std               18.919944          17.707988            7.272384   
min                0.000000          -9.276106            1.000000   
25%               22.400790          65.175823            7.000000   
50%               28.771184          73.029570           10.000000   
75%               36.383680          82.173420           12.000000   
max              118.414671         118.863496           49.000000   

              Age  Prior_Programming_Experience_Yrs  Online_Courses_Completed  
count  500.000000                        500.000000                500.000000  
mean    26.434000                          1.788520                  2.938000  
std      4.874954                          1.867475                  1.655184  
min     18.000000                          0.002475                  0.000000  
25%     22.000000                          0.495720                  2.000000  
50%     26.000000                          1.227495                  3.000000  
75%     31.000000                          2.423013                  4.000000  
max     34.000000                         11.775799                 11.000000

In [23]:
average = np.mean(data['Study_Hours_Per_Week'])
print(f'Average study hours: {average:.1f} hours')

Average study hours: 31.9 hours


In [46]:
# data.groupby('Student_ID')[(data['Prior_Programming_Experience_Yrs']>3).sum()]