# Task 13

In [15]:
import numpy as np
import matplotlib.pyplot as plt
import time

np.set_printoptions(precision=3, suppress=True)

### Question 1

1. Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.

In [16]:
#A 6X6 Numpy array

arr = np.random.randint(50, size=(6,6))
print(f"Random numbers between 1 and 50:\n{arr}")


Random numbers between 1 and 50:
[[46 20  4 13  1 21]
 [18 40  1  7  1 32]
 [ 2  6 42 15 19 31]
 [13 45  1 11 31  6]
 [44 37  1 34 13 35]
 [38 20  2  2 35  1]]


### Question 2


2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.


In [17]:
print(f"First 2 rows: \n{arr[0:2, :]}")
print(f"\nLast three columns: \n{arr[:, 3:]}")
print(f"\nEven numbers in the array: \n{arr[arr%2 == 0]}")


First 2 rows: 
[[46 20  4 13  1 21]
 [18 40  1  7  1 32]]

Last three columns: 
[[13  1 21]
 [ 7  1 32]
 [15 19 31]
 [11 31  6]
 [34 13 35]
 [ 2 35  1]]

Even numbers in the array: 
[46 20  4 18 40 32  2  6 42  6 44 34 38 20  2  2]


### Question 3

3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

In [18]:
#Reshaping into 3D
print(f"Reshaped into 3D:\n{arr.reshape(3,2,6)}")

#Flattening into 1D
flat = arr.flatten()
print(f"\nFlattened: \n{flat}")

Reshaped into 3D:
[[[46 20  4 13  1 21]
  [18 40  1  7  1 32]]

 [[ 2  6 42 15 19 31]
  [13 45  1 11 31  6]]

 [[44 37  1 34 13 35]
  [38 20  2  2 35  1]]]

Flattened: 
[46 20  4 13  1 21 18 40  1  7  1 32  2  6 42 15 19 31 13 45  1 11 31  6
 44 37  1 34 13 35 38 20  2  2 35  1]


### Question 4

4. Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [19]:
identity = np.eye(4)

np.fill_diagonal(identity, (np.arange(10,50,10)))
print(identity)


[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


### Question 5

5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [20]:
#Matrix multiplication
mat1 = np.random.randint(1,10, size=(3,4))
mat2 = np.random.randint(1,10, size=(4,3))
mult = np.dot(mat1,mat2)

print(f"\n3x4 array: \n{mat1}")
print(f"\n4x3 array: \n{mat2}")
print(f"\nMultiplication: \n{mult}")


3x4 array: 
[[9 6 7 5]
 [3 1 3 7]
 [4 8 6 1]]

4x3 array: 
[[9 5 1]
 [9 7 6]
 [4 7 8]
 [8 5 2]]

Multiplication: 
[[203 161 111]
 [104  78  47]
 [140 123 102]]


### Question 6

6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

In [ ]:
def array_manipulator(arr2d):
    #this reshapes the inputted 1D array into a 2 by x array
    array = np.array(arr2d).reshape(2,-1)

    #this checks for even numbers and replaces it with the square of that even number or it replaces the odd numbers with -1
    output = np.where(array %2 == 0, array**2, -1 )
    return f"Latest array: \n{output}"

list_array = []
for i in range(4):
    arr2 = int(input("Enter four numbers: "))
    list_array.append(arr2)

print(list_array)
print(array_manipulator(list_array))
    