# Understanding Numpy

In [10]:
#importing all necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import time

#Checking numpy version
print(f"Numpy version: {np.__version__}")

#Display settings for cleaner output
#the print options make arrays display more readable by limiting decimal places
np.set_printoptions(precision=3, suppress=True)

Numpy version: 2.3.2


### Creating Numpy Arrays

In [11]:
#CREATING ARRAYS FROM PYTHON LISTS
#1D array: a simple sequence of numbers
array_1D = np.array([1,2,3,4])

#2D array: this a matrix or a table with rows and columns
array_2D = np.array([[1,2], [3,4]])

#3D array: is like a stack of 2D arrays, they're useful for images, time series, etc.
array_3D = np.array([[[1,2], [3,4]],
                     [[5,6], [7,8]]])

print(f"1D array: {array_1D}")
print(f"2D array:\n {array_2D}")
print(f"2D array:\n{array_3D}")

1D array: [1 2 3 4]
2D array:
 [[1 2]
 [3 4]]
2D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Creating special arrays in numpy

In [ ]:
# Creating arrays filled with zeros, this is used for initializin arrays
#this creates a 3x4 matrix filled with zeros
zeros = np.zeros((3,4))

#Creating arrays filled with ones, this is often used as starting points 
#this creates a 3x4 3D matrix with two layers
ones = np.ones((2,3,4))

#empty array: this is faster than zeros/ones, it fills a matrix with random values
#this fills a 2x2 matrix with random values
emptyy = np.empty((2,2))

print(emptyy)
# print(ones)
# print(zeros)


[[0. 0.]
 [0. 0.]]


In [24]:
#Range arrays
range_arr = np.arange(0,10,2) #start,stop,step
print(f"Range array: {range_arr}")

#Linearly spaced arrays, this divides a range into equal parts
#this divides the values between zero and one into 5 equal parts
linspace_arr = np.linspace(0,1,5)
print(f"Linspace array: {linspace_arr}")

#Logarithmically spaced arrays, this is useful for scientific data
logspace_arr = np.logspace(0, 1, 6)
print(logspace_arr)

Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
[ 1.     1.585  2.512  3.981  6.31  10.   ]


In [29]:
#Identity matrix: diagnoal of ones, zeros elsewhere. This is essential for linear algebra operations
identity = np.eye(4) #this creates a 4x4 identity matrix

#Diagonal matrix: this puts values on the diagonal
diagonal = np.diag([1,2,3,4])

#Array filled with specific values
full_arr = np.full((3,3), 7) #fills a 3x3 matrix with 7s
print(identity)
print(f"Diagonal matrix: \n{diagonal}")
print(f"Full array (filled with 7): \n{full_arr}")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7): 
[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Numpy Data Types

In [39]:
#Explicit data types: controls memory usage and precision
int_arr = np.array([1,2,3], dtype=np.int32) #this sets the data type to int32
float_arr = np.array([1,2,3], dtype=np.float64) #this sets the data type to float64
bool_arr = np.array([True, False, True], dtype=np.bool_)

#Type conversion
converted = int_arr.astype(np.float32) #converts the int data type to float32

print(int_arr.dtype)
print(f"Float array dtype: {float_arr.dtype}")
print(f"Boolean array data type: {bool_arr.dtype}")
print(f"Converted array dtype: {converted.dtype}")

#Memory usage comparison
print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")

int32
Float array dtype: float64
Boolean array data type: bool
Converted array dtype: float32
int32 uses 4 bytes per element
float64 uses 8 bytes per element
