# Understanding Numpy

In [2]:
#importing all necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import time

#Checking numpy version
print(f"Numpy version: {np.__version__}")

#Display settings for cleaner output
#the print options make arrays display more readable by limiting decimal places
np.set_printoptions(precision=3, suppress=True)

Numpy version: 2.3.2


### Creating Numpy Arrays

In [11]:
#CREATING ARRAYS FROM PYTHON LISTS
#1D array: a simple sequence of numbers
array_1D = np.array([1,2,3,4])

#2D array: this a matrix or a table with rows and columns
array_2D = np.array([[1,2], [3,4]])

#3D array: is like a stack of 2D arrays, they're useful for images, time series, etc.
array_3D = np.array([[[1,2], [3,4]],
                     [[5,6], [7,8]]])

print(f"1D array: {array_1D}")
print(f"2D array:\n {array_2D}")
print(f"2D array:\n{array_3D}")

1D array: [1 2 3 4]
2D array:
 [[1 2]
 [3 4]]
2D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Creating special arrays in numpy

In [ ]:
# Creating arrays filled with zeros, this is used for initializin arrays
#this creates a 3x4 matrix filled with zeros
zeros = np.zeros((3,4))

#Creating arrays filled with ones, this is often used as starting points 
#this creates a 3x4 3D matrix with two layers
ones = np.ones((2,3,4))

#empty array: this is faster than zeros/ones, it fills a matrix with random values
#this fills a 2x2 matrix with random values
emptyy = np.empty((2,2))

print(emptyy)
# print(ones)
# print(zeros)


[[0. 0.]
 [0. 0.]]


In [24]:
#Range arrays
range_arr = np.arange(0,10,2) #start,stop,step
print(f"Range array: {range_arr}")

#Linearly spaced arrays, this divides a range into equal parts
#this divides the values between zero and one into 5 equal parts
linspace_arr = np.linspace(0,1,5)
print(f"Linspace array: {linspace_arr}")

#Logarithmically spaced arrays, this is useful for scientific data
logspace_arr = np.logspace(0, 1, 6)
print(logspace_arr)

Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
[ 1.     1.585  2.512  3.981  6.31  10.   ]


In [29]:
#Identity matrix: diagnoal of ones, zeros elsewhere. This is essential for linear algebra operations
identity = np.eye(4) #this creates a 4x4 identity matrix

#Diagonal matrix: this puts values on the diagonal
diagonal = np.diag([1,2,3,4])

#Array filled with specific values
full_arr = np.full((3,3), 7) #fills a 3x3 matrix with 7s
print(identity)
print(f"Diagonal matrix: \n{diagonal}")
print(f"Full array (filled with 7): \n{full_arr}")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7): 
[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Numpy Data Types

In [39]:
#Explicit data types: controls memory usage and precision
int_arr = np.array([1,2,3], dtype=np.int32) #this sets the data type to int32
float_arr = np.array([1,2,3], dtype=np.float64) #this sets the data type to float64
bool_arr = np.array([True, False, True], dtype=np.bool_)

#Type conversion
converted = int_arr.astype(np.float32) #converts the int data type to float32

print(int_arr.dtype)
print(f"Float array dtype: {float_arr.dtype}")
print(f"Boolean array data type: {bool_arr.dtype}")
print(f"Converted array dtype: {converted.dtype}")

#Memory usage comparison
print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")

int32
Float array dtype: float64
Boolean array data type: bool
Converted array dtype: float32
int32 uses 4 bytes per element
float64 uses 8 bytes per element


### Array Properties and Atrributes

In [11]:
#Create  sample 3D array for demonstration
#this creates a 3 layered 3D array of 4x5 matrix containing random numbers
arr = np.random.randn(3,4,5)

#Shape: the dimensions of the array (layers, row, columns)
print(f"Shape: {arr.shape}")

#Size: gives the total number of elements (3x4x5 = 60)
print(f"Size {arr.size}")

#Ndim: Number of dimensions (in this case: 3D)
print(f"Ndim: {arr.ndim}")

#Dtype: Data types of elements
print(f"Dtype: {arr.dtype}")

#Itemsize: fives the memory size of each element in bytes
print(f"Itemsize: {arr.itemsize}") #each element has 8 bytes

#Total memory usage in bytes
print(f"Memory usage: {arr.nbytes} bytes.")
print(f"Memory usage: {arr.nbytes/1024} kilobytes.") #converting to KB
# print(arr)

Shape: (3, 4, 5)
Size 60
Ndim: 3
Dtype: float64
Itemsize: 8
Memory usage: 480 bytes.
Memory usage: 0.46875 kilobytes.


### Array Indexing and Slicing
#### Basic indexing: accessing individual elements

In [15]:
#1D array indexing is similar to Python lists
arr1D = np.array([10, 20, 30, 40, 50])

print(f"First element: {arr1D[0]}")
print(f"Last element: {arr1D[-1]}")
print(f"Slice [1:4] {arr1D[1:4]}")
print(f"Every 2nd element: {arr1D[::2]}")

First element: 10
Last element: 50
Slice [1:4] [20 30 40]
Every 2nd element: [10 30 50]


In [24]:
# 2D array indexing: row and column access
arr2D = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

#Accessing specific elements: [row, column]
print(f"Element at row1, column2: {arr2D[1,2]}") #7

#Accessing entire rows or columns
print(f"First row: {arr2D[0, :]}")
print(f"Second column: {arr2D[:, 1]}") #prints 2 6 10

#Subarry slicing: [row_start:row_end, column_start:column_end]
print(f"Subarray (rows 1-2, cols 1-2): \n{arr2D[1:3, 1:3]}")

Element at row1, column2: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Subarray (rows 1-2, cols 1-2): 
[[ 6  7]
 [10 11]]


#### Advanced Indexing: powerful selection methods

In [ ]:
#Fancy indexing: use arrays of indices to select elements
arr = np.array([10,20,30,40,50])
indices = np.array([0,2,4])
print(f"Fancy indexing: {arr[indices]}")

#this is much more flexible than simple slicing
random_indices = np.array([4,1,3,1])
print(f"Random order: {arr[random_indices]}") #[50, 20, 40, 20]

Fancy indexing: [10 30 50]
Random order: [50 20 40 20]


In [ ]:
#2D fancy indexing: select specific row/column combinations
#this shapes a 1D array gotten through arange(12) into 3x4
arr2D = np.arange(12).reshape(3,4)
print(f" Original 2D array: \n{arr2D}")

#Select element at (row, col) pairs: (0,1) and (2,3)
rows = np.array([0,2])
cols = np.array([1,3])
#this prints out the elements at row 0 col 2, and row 2 column 3
print(f"Element at (0,1) and (2,3): {arr2D[rows, cols]}")

#Selecting entire rows using fancy indexing
selected_rows = arr2D[[0,2], :] #this prints out the contents of row 0 and row 2
print(f"Selected rows: \n{selected_rows}")


 Original 2D array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at (0,1) and (2,3): [ 1 11]
Selected rows: 
[[0 1 2 3]
 [4 5 6 7]]


### Array Reshaping and Manipulation

In [52]:
#Reshaping changes how the same data is organized in memorey without changing the actual values

#Starting with a 1D array
arr = np.arange(12)
print(f"Original 1D array: {arr}")

#Reshaping to a 2D 3x4 array
reshaped_2d = arr.reshape(3,4)
print(f"Reshaped to 3x4: \n{reshaped_2d}")

#Reshaping to 2 layered 3D 2x3 array
reshaped_3d = arr.reshape(2,2,3)
print(f"Reshaped to 2x2x3: \n{reshaped_3d}")

#Using -1 to let NumPy calculate one dimension automatically
auto_reshape = arr.reshape(4, -1) #inputted 4 as the number of rows, Numpy calculates the number of columns required
print(f"Auto-reshaped to 4x?:\n {auto_reshape}")


Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x2x3: 
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Auto-reshaped to 4x?:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [54]:
#Flattening: converts multi-dimensional arrays to 1D
arr2d = np.array([[1,2,3], [4,5,6]])

#Flatten() always returns a copy
flattened = arr2d.flatten()
print(f"Flattened (copy): {flattened}")

#Ravel() returns a view if possible (this is faster and more efficient)
ravel = arr2d.ravel()
print(f"Ravel (view if possible): {ravel}")

Flattened (copy): [1 2 3 4 5 6]
Ravel (view if possible): [1 2 3 4 5 6]


### Transposing and Swapping Axes

In [58]:
#2D tranposition: flips rows and columns
arr2d = np.array([[1,2,3], [4,5,6]])
print(f"Original shape: {arr2d.shape}")
print(f"Original: \n{arr2d}")

print(f"Transposed shape: {arr2d.T.shape}")
print(f"Transposed: \n{arr2d.T}")

#Alternative transpose methods
print(f"Transpose methods: \n{arr2d.transpose()}")

Original shape: (2, 3)
Original: 
[[1 2 3]
 [4 5 6]]
Transposed shape: (3, 2)
Transposed: 
[[1 4]
 [2 5]
 [3 6]]
Transpose methods: 
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Higher dimensional transposition
arr3d = np.arange(24).reshape(2,3,4)
print(arr3d)
print(arr3d.shape)

#Specifying new axis order : (axis0, axis1, axis3) → (axis2, axis0, axis1)
transposed_3d = arr3d.transpose(2,0,1) #this becomes 4 layers, 2 rows, and 3 columns
print(f"Transposed 3D: \n{transposed_3d.shape}")

#Moved axis 


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
Transposed 3D: 
(4, 2, 3)
